apiVersion: v1
kind: Service
metadata:
  name: sidecar-renderer-app-service
  namespace: local
spec:
  type: NodePort
  selector:
    app: sidecar-renderer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-renderer-app-deployment
  namespace: local
  labels:
    app: sidecar-renderer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-renderer-app
  template:
    metadata:
      labels:
        app: sidecar-renderer-app
    spec:
      volumes:
      - name: sidecar
        emptyDir: {}
      containers:
      - name: sidecar-renderer-app
        volumeMounts: 
          - name: sidecar
            mountPath: /tmp
        image: sidecar-renderer-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      - name: sidecar-renderer-sidecar
        volumeMounts: 
          - name: sidecar
            mountPath: /tmp
        image: sidecar-renderer-sidecar:latest
        imagePullPolicy: IfNotPresent