apiVersion: v1
kind: Service
metadata:
  name: sidecar-renderer-app-service
  namespace: local
spec:
  type: NodePort
  selector:
    app: sidecar-renderer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-renderer-app-deployment
  namespace: local
  labels:
    app: sidecar-renderer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-renderer-app
  template:
    metadata:
      labels:
        app: sidecar-renderer-app
    spec:
      containers:
      - name: sidecar-renderer-app
        image: sidecar-renderer-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000